### ISSUE TITLE
Bug conversão

### ISSUE THREAD

**Issue by vitorvsv** [vitorvsv/math_algorithm#3]
Ao selecionar o algoritmo de decimal para binário (inteiro) e colocando como valor de entrada o número 78. É gerado um valor binário incorreto.

**Comment by Flucons** [comment]
Minha culpa, devido a mudança dos operados de comparação. Creio que o que está acontecendo é que o valor recebido pela variável _number_ na função _calculate_ é do tipo string e não number, aí quando mudei os operadores de comparação para os que levam em conta o tipo da variável começou o problema.
Creio que mudar a declaração de _q_ na função _algorithm2_ para: `var q = Number(number);` deva resolver a questão.

**Comment by vitorvsv** [comment]
Tranquilo, já fiz um push com o ajuste nesse bug.
